<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SonarQubeTestProject>false</SonarQubeTestProject>
    <NoWarn>1591;NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="dist\**" />
    <Content Remove="dist\**" />
    <EmbeddedResource Remove="dist\**" />
    <None Remove="dist\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Localizations\**">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.CatalogQuality.Core\VirtoCommerce.CatalogQuality.Core.csproj" />
    <ProjectReference Include="..\VirtoCommerce.CatalogQuality.Data\VirtoCommerce.CatalogQuality.Data.csproj" />
    <ProjectReference Include="..\VirtoCommerce.CatalogQuality.Data.MySql\VirtoCommerce.CatalogQuality.Data.MySql.csproj" />
    <ProjectReference Include="..\VirtoCommerce.CatalogQuality.Data.PostgreSql\VirtoCommerce.CatalogQuality.Data.PostgreSql.csproj" />
    <ProjectReference Include="..\VirtoCommerce.CatalogQuality.Data.SqlServer\VirtoCommerce.CatalogQuality.Data.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ai\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <AiFolder Include="ai\**" />
  </ItemGroup>

  <Target Name="CopyCustomContentOnPublish" AfterTargets="Publish">
    <Copy SourceFiles="@(AiFolder)" DestinationFiles="$(PublishDir)\..\%(Identity)" />
  </Target>
  
</Project>
